---
# Items that apply to ALL profiles:
eureka:
  client:
    serviceUrl:
#      defaultZone: http://localhost:8010/eureka/
      defaultZone: http://localhost:8011/eureka/,http://localhost:8012/eureka/,http://localhost:8013/eureka/

---
spring.config.activate.on-profile: subject
words: I,You,He,She,It
  
---
spring.config.activate.on-profile: verb
words: ran,knew,had,saw,bought

---
spring.config.activate.on-profile: article
words: a,the

---
spring.config.activate.on-profile: adjective
words: reasonable,leaky,suspicious,ordinary,unlikely

---
spring.config.activate.on-profile: noun
words: boat,book,vote,seat,backpack,partition,groundhog
  
